" Shared config, sourced by BOTH classic Vim (~/.vimrc) and Neovim
" (nvim/init.lua sources this file). Keep this file plain vimscript only
" (no Lua, no plugin-manager calls) so it works identically in both.
" Plugin declarations live in vim/plugins.vim (classic Vim only) and
" nvim/lua/user/plugins/* (Neovim only).

syntax on
filetype plugin indent on
set number
set nocursorline
set autoindent
set smartindent
set ruler
set ts=2 sts=2 sw=2 bs=2
set backspace=indent,eol,start

set backup
if has('win32') || has('win64')
  set backupdir=~/vimfiles/backup
  set directory=~/vimfiles/tmp
else
  set backupdir=~/.vim/backup
  set directory=~/.vim/tmp
endif

" disable error bells (especially annoying under WSL on Windows)
set noerrorbells
set novisualbell
set vb t_vb=
set belloff=all

nmap H :tabp<enter>
nmap L :tabn<enter>
nmap <c-o> o<esc>
map J 10j
map K 10k

" clear last search
nmap <C-n> :let @/ = ""<enter>

" format code of the current file
nmap X mzgggqG`z

hi RubySymbol term=none cterm=none ctermfg=darkYellow

autocmd FileType java    set ts=4
autocmd FileType java    set sts=4
autocmd FileType java    set sw=4
autocmd FileType java    set bs=4

" Renames current file
command -nargs=+ -complete=file To let originalfilename = expand('%:q')|f <args>/%:t|w|call delete(originalfilename)

" Deletes current file
command -nargs=0 Del call delete(expand('%:p'))|q

" Fixing common typos
iab lenght length
iab widht width
iab heigth height

" expandtab for these filetypes
au FileType ruby,javascript,python,html,erb,yaml,yml,playbook,lua,eruby,elixir,pub,hbs,handlebars,cs set expandtab

" convert tabs to spaces on read/write for these filetypes
au BufRead,BufWrite *.rb,*.js,*[rR]akefile,*.py,*.yml,*.playbook,*.lua,*.html*,*.erb*,*.ex,*.exs,*.eex,*.pub,*.cs retab

" trailing whitespace shows up in red
au BufNewFile,BufRead * syn match brancomala '\s\+$' | hi brancomala ctermbg=red

" In visual mode when you press * or # to search for the current selection
vnoremap <silent> * :call VisualSearch('f')<CR>
vnoremap <silent> # :call VisualSearch('b')<CR>

" From an idea by Michael Naumann
function! VisualSearch(direction) range
    let l:saved_reg = @"
    execute "normal! vgvy"

    let l:pattern = escape(@", '\\/.*$^~[]')
    let l:pattern = substitute(l:pattern, "\n$", "", "")

    if a:direction == 'b'
        execute "normal ?" . l:pattern . "^M"
    elseif a:direction == 'gv'
        call CmdLine("vimgrep " . '/'. l:pattern . '/' . ' **/*.')
    elseif a:direction == 'f'
        execute "normal /" . l:pattern . "^M"
    endif

    let @/ = l:pattern
    let @" = l:saved_reg
endfunction

" Classic-Vim-only plugins (never loaded under Neovim, which uses lazy.nvim)
if !has('nvim')
  execute 'source ' . fnameescape(expand('<sfile>:p:h') . '/plugins.vim')
endif
